services:
  - type: web
    name: ryne-token-extractor
    env: docker
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'true'
      - key: NODE_ENV
        value: production
    healthCheckPath: /status
    autoDeploy: true
