services:
  - type: web
    name: ryne-token-extractor
    env: docker
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /tmp/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'false'
      - key: NODE_ENV
        value: production
    healthCheckPath: /status
    autoDeploy: true
